# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcmt < Formula
  desc "Fork of mercari/tfnotify. tfcmt enhances tfnotify in many ways, including Terraform >= v0.15 support and advanced formatting options
"
  homepage "https://github.com/suzuki-shunsuke/tfcmt"
  version "3.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.2.3/tfcmt_darwin_amd64.tar.gz"
      sha256 "61f9d600eee544da029772353cac971d3bf082633138646561600d64f45afd87"

      def install
        bin.install "tfcmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.2.3/tfcmt_darwin_arm64.tar.gz"
      sha256 "6ca4ad63ae52bb70318662f560cf5ad378dcde0cd08c118dd80907a4b0aef26d"

      def install
        bin.install "tfcmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.2.3/tfcmt_linux_amd64.tar.gz"
      sha256 "de89f24b21dc513c66c6fbc635f7bcb04daba1cfaa5bfc5a4a89a8d94f908791"

      def install
        bin.install "tfcmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v3.2.3/tfcmt_linux_arm64.tar.gz"
      sha256 "b5d684186685380f60e88d6f04c6f8e7d00af966a36080b26bb24d80d990d06b"

      def install
        bin.install "tfcmt"
      end
    end
  end

  test do
    system "#{bin}/tfcmt --version"
  end
end
