# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfcmt < Formula
  desc "Fork of mercari/tfnotify. tfcmt enhances tfnotify in many ways, including Terraform >= v0.15 support and advanced formatting options
"
  homepage "https://github.com/suzuki-shunsuke/tfcmt"
  version "4.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.6.0/tfcmt_darwin_amd64.tar.gz"
      sha256 "7f51bc501f7e4ac6324ac1992f31c76a57b08c38ce4c2eb3fede7f957cf9f9c4"

      def install
        bin.install "tfcmt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.6.0/tfcmt_darwin_arm64.tar.gz"
      sha256 "89b8e1096bc4dbac908e884df58690b76910d2385c2eef3e3438231cafc4f86c"

      def install
        bin.install "tfcmt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.6.0/tfcmt_linux_amd64.tar.gz"
      sha256 "09e713daa02e2d63118e3284538f9f27e4f2713591d44c20ca767ad70acad969"

      def install
        bin.install "tfcmt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.6.0/tfcmt_linux_arm64.tar.gz"
      sha256 "31cabcbdf5db80cdb6ddc0f695bd6ae7b948c86fd4ac298ec910a7bac9150a1a"

      def install
        bin.install "tfcmt"
      end
    end
  end

  test do
    system "#{bin}/tfcmt --version"
  end
end
