# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcmt" do
  name "tfcmt"
  desc "Fork of mercari/tfnotify. tfcmt enhances tfnotify in many ways, including Terraform >= v0.15 support and advanced formatting options
"
  homepage "https://github.com/suzuki-shunsuke/tfcmt"
  version "4.14.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcmt"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_darwin_amd64.tar.gz"
      sha256 "7406e0ce99e3d46df094b0b7598bb55aeb9bf2116d7f0bc4fb92b4d273e11493"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_darwin_arm64.tar.gz"
      sha256 "d38934a679da0e3a8c9b36f11edeb5728b6d60f2727bc58b5f88b930108fddd0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_linux_amd64.tar.gz"
      sha256 "08e0ac75a743fde6948d8482f992c90b8bee5e99fe1b5e4de11ccea428e66a86"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_linux_arm64.tar.gz"
      sha256 "37ca2c63936ae269774c8d32a7d6d42a45ccdb7ee7fd7721a403619e884b2f25"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfcmt"]
    end
  end

  # No zap stanza required
end
