# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcmt" do
  name "tfcmt"
  desc "Fork of mercari/tfnotify. tfcmt enhances tfnotify in many ways, including Terraform >= v0.15 support and advanced formatting options
"
  homepage "https://github.com/suzuki-shunsuke/tfcmt"
  version "4.14.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcmt"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_darwin_amd64.tar.gz"
      sha256 "93e8da3a3295d8bdb49964a208d6dcbe0085da66be50570f2f93a1ba2f5389c1"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_darwin_arm64.tar.gz"
      sha256 "5e97d03f8d1c60afd33f19aeac5424c4dbeed6fb0aaa8cc5d79f430e79d6fd0f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_linux_amd64.tar.gz"
      sha256 "475e3fb36765b10fec5c7a199f86116f6ef764340f96d6baa2becf609418b760"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v#{version}/tfcmt_linux_arm64.tar.gz"
      sha256 "33c25b19b1100f6b4e3313d364a56b034f2c1b711281c861102123b9c8c1a764"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfcmt"]
    end
  end

  # No zap stanza required
end
