# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfcmt" do
  desc "Fork of mercari/tfnotify. tfcmt enhances tfnotify in many ways, including Terraform >= v0.15 support and advanced formatting options
"
  homepage "https://github.com/suzuki-shunsuke/tfcmt"
  version "4.14.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfcmt"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.10/tfcmt_darwin_amd64.tar.gz"
      sha256 "4f1154e9ab93ae1bfbe293fdb7f30c15acec0b26b0948021ce1fe242e0780dd3"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.10/tfcmt_darwin_arm64.tar.gz"
      sha256 "a5dbb526e669fab68bfea69210f6b336166d152a25dc643ff0520abf4e0e6c1f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.10/tfcmt_linux_amd64.tar.gz"
      sha256 "3eac422478c90dc89225cfad47e24f21246ca43765461be1c1a412b6eb3db0a7"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.14.10/tfcmt_linux_arm64.tar.gz"
      sha256 "6a3595ceed81a532700be096856143e82b722163fd406787f1ef3d0c7a725dce"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfcmt"]
    end
  end

  # No zap stanza required
end
